// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCK5KJI9ZnCzqqk3j7QpcfQhwLFWUqXA3w',
    appId: '1:878723598010:web:7fbd8b52760d99e2156483',
    messagingSenderId: '878723598010',
    projectId: 'mychatapp-56cd5',
    authDomain: 'mychatapp-56cd5.firebaseapp.com',
    storageBucket: 'mychatapp-56cd5.appspot.com',
    measurementId: 'G-MZVWJQPVLG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJ68nCcvQVgmQpuOmSX_sMCltDf4ycq4c',
    appId: '1:878723598010:android:95d216f54efd8525156483',
    messagingSenderId: '878723598010',
    projectId: 'mychatapp-56cd5',
    storageBucket: 'mychatapp-56cd5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYGOmsIdft5eWGq7VVIoqVL_rxPbcTdwo',
    appId: '1:878723598010:ios:f2e2dfce2dce2ba6156483',
    messagingSenderId: '878723598010',
    projectId: 'mychatapp-56cd5',
    storageBucket: 'mychatapp-56cd5.appspot.com',
    iosBundleId: 'com.example.mychatApp',
  );
}
